### ISSUE TITLE
Cryptic error when using .bsts with arches

### ISSUE THREAD

**Issue by cs-shadow** [cs-shadow/buildstream#123]
In GitLab by @aevri on Oct 19, 2017, 09:15

When trying to load a pipeline with an element specifying the old 'arches' statements, a cryptic error is emitted:

```
KeyError: "Key not found in the first mapping: 'kind'"
```

I'd expect something more along the lines of:

```
Error loading pipeline: [arches.bst [line 3 column 1]]: Unexpected key: arches
```

Repro'd using empty project and single `arches.bst`:

```
kind: import
description: Import tar
arches:
  x86_64:
    sources:
    - kind: tar
      url: https://server.example/tar.tar.gz
      base-dir: ""
```

Tested at a243a3335b7c113a49b1d5f0daa2c11efe2299bd, '.gitlab-ci.yml: Issue #100 - Avoid installing setup.py test_requires'.

Broken since 4488ddf55034c4b00c9ce221f303f205e13c85a9, '_yaml.py: Implement array composition directives'.
