### ISSUE TITLE
Remove 'arches' conditionals

### ISSUE THREAD

**Issue by cs-shadow** [cs-shadow/buildstream#124]
In GitLab by @tristanvb on Oct 19, 2017, 13:43

This is replaced by project options.

One should use 'arch' type project options to implement arch specific conditionals.

**Comment by cs-shadow** [comment]
In GitLab by @tristanvb on Oct 19, 2017, 13:46

mentioned in merge request !117

**Comment by cs-shadow** [comment]
In GitLab by @bochecha on Oct 29, 2017, 23:00

Just found out about this, and I'm a bit surprised.

At the moment I'm using something like this:

```
$ cat elements/foo.bst
kind: import

arches:
  arm:
    sources:
    - kind: ostree
      url: https://foo.com/
      track: foo/arm/devel
  x86_64:
    sources:
    - kind: ostree
      url: https://foo.com/
      track: foo/x86_64/devel
```

Then I can build with `bst --arch=arm build bar.bst` (`bar` depends on `foo`) even on my x86_64 laptop and it would just work (I have the qemu-user-static stuff setup)

It seems (but I feel like I'm guessing, because I find the docs to be extremely unclear on this) that if I added this snippet to my `project.conf`:

```
options:
  machine_arch:
    type: arch
    values:
    - arm
    - x86_64
    variable: arch
```

... then I could replace my `foo.bst` declarations by:

```
sources:
- kind: ostree
  url: https://foo.com
  track: foo/%{arch}/devel
```

(and if the above is actually how things work, then it's certainly much nicer to write/maintain than the current `arches` conditionals :slight_smile:)

However, the second part seems to be missing: this pull request completely removes the `--arch` option, how can I explicitly specify the arch to build for?

Apologies if this is all documented, I really couldn't find it. :confused:

**Comment by cs-shadow** [comment]
In GitLab by @tristanvb on Oct 30, 2017, 06:33

So there are two answers to this...


### Use separated dictionaries

First, I recommend using conditional statements for this, e.g.:

```
(?):
- machine_arch == "i386":
    sources:
    - kind: ostree
      url: aliasname:repodir
      track: foo/i386/devel
- machine_arch == "x86_64":
    sources:
    - kind: ostree
      url: aliasname:repodir
      track: foo/x86_64/devel
```

Because in situations where you want to make a release tag of your project, with all source references tracked and referring to an exact build which you might want to repeat - then `bst track` will have a nicely separate dictionary in which to dump the reference (i.e. the `ref:` field) for each architecture.

### Variables are not everywhere

It turns out that this is a bit confusing, maybe we should change it - I've been pondering this for a while and wondering if it would be "safe" to just allow variable substitution across the board, perhaps removing [Element.node_subst_member()](http://buildstream.gitlab.io/buildstream/buildstream.element.html#buildstream.element.Element.node_subst_member) and making [Plugin.node_get_member()](http://buildstream.gitlab.io/buildstream/buildstream.plugin.html#buildstream.plugin.Plugin.node_get_member) perform the substitutions unconditionally (in fact, Sources never gained the capability to interpret yaml with variable substitutions at all, but I suppose they can use the resolved variables of their owning elements).

This would be a bit tricky because we'd have to somehow reorder type coercion and type checking to occur only after variable substitution happens (currently anything that is intentionally substituted is assumed to be a string).

However, this is not the first time I've noticed the expectation, from a project authoring point of view, that `%{variable-name}` expansion would just be supported everywhere in the format across the board, so I'm hoping that changing our format to meet that natural expectation can be safely done.
