### ISSUE TITLE
Error when trying to use list prepend to replace pre-* commands in project.conf

### ISSUE THREAD

**Issue by cs-shadow** [cs-shadow/buildstream#131]
In GitLab by @hashpling on Oct 24, 2017, 08:03

Following issue #121, I was looking to replace a use of a `pre-` command in the `elements` section of a project.conf. The intention is to add an extra step project-wide for a particular kind of build, in this case the built in "autotools" kind.

Very cut down, this project.conf demonstrates the issue:

```yaml
name: testcase

# [...]

elements:
  autotools:
    config:
      pre-configure-commands:
      - echo "About to configure!"
```

This works correctly and my custom command is run before the configure step. If I change this as follows I get an error: "Error loading project: /src/project.conf [line 17 column 8]: Attempt to override non-existing list".

```yaml
elements:
  autotools:
    config:
      configure-commands:
        (<):
        - echo "About to configure!"
```

If I remove the `(<):` line then my custom command replaces the autotools plugin `configure-commands` and the project does not build correctly.

Is this a bug or have I misunderstood the configuration composition or the list directives?
