### ISSUE TITLE
Add `all` value to depends `type`

### ISSUE THREAD

**Issue by cs-shadow** [cs-shadow/buildstream#65]
In GitLab by @sstriker on Aug 4, 2017, 15:44

When you specify a dependency the default is to have it be available in both `build` and `run`.  There is no way to explicitly state `all`, you need to leave `type` undefined.  We propose the ability to use the syntax below so one can be explicit.

```yaml
kind: manual

depends:
- filename: b.bst
  type: all
```
