### ISSUE TITLE
Extend the `tar` and `zip` source plugins to include `etag` support

### ISSUE THREAD

**Issue by cs-shadow** [cs-shadow/buildstream#66]
In GitLab by @sstriker on Aug 4, 2017, 16:01

When tracking a `tar` source, store the contents of the [ETag](https://tools.ietf.org/html/rfc7232#section-2.3) response header in an `etag` field, next to the ref.  When tracking, and we have a file on disk already, also use an already present `etag` value in the [If-None-Match](https://tools.ietf.org/html/rfc7232#section-3.2) request header.  Handle HTTP 304 response to mean to use the file we already have on disk.  This way we avoid having to download typically large files over and over again.
Avoiding that in the case of `bst build --track` is particularly beneficial.

Example:
```yaml
...

sources:
- kind: tar
  url: "https://example.com/my_big_tarball.tar.gz"
  ref: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b 
  etag: "adc83b19e793491b1c6ea0fd8b46cd9f32e592fc"
```
