### ISSUE TITLE
Domain inclusion seem to not work

### ISSUE THREAD

**Issue by cs-shadow** [cs-shadow/buildstream#82]
In GitLab by @bochecha on Aug 27, 2017, 10:20

I've got the following in my `project.conf`: 

```yaml
split-rules:
  devel:
  # Those are the default BuildStream ones
  - |
    %{includedir}
  - |
    %{includedir}/**
  - |
    %{libdir}/lib*.a
  - |
    %{libdir}/lib*.la
  - |
    %{libdir}/pkgconfig/*.pc
  - |
    %{datadir}/pkgconfig/*.pc
  - |
    %{datadir}/aclocal/*.m4
  # Those are the ones I added
  - |
    %{bindir}/*gcc*
  - |
    %{libexecdir}/gcc
```

I have a `compose` element with:

```yaml
config:
  include:
  - runtime
  - locale
```

I would expect that element not to have any of the things I added to the `devel` domain. And yet, when I `bst checkout` it, there they are.

Am I doing something wrong? Or did I stumble upon a bug?

(edited to explicitly mention I was using a `compose` element)
